In [ ]:
def inp(options):
    print(options[0])
    for option in options[1: -1]:
        print(f'\t{option}`)
    valid = ''.join(option[1] for option in options[1: -1])
    while True:
        option = input('> ').strip().lower()
        


options = ["Calculate from what (choose two)?", 
           "[g]ross amount", 
           "[n]et amount", 
           "[r]ate",
           "[t]ax amount",
           "[q]uit",
            ]

def try_this(expression, tax):
	'''
	Evaluates an expression and return None instead of raising an error if an exception is triggered (such as trying to perform an operation with NoneValue).
	'''
	try:
		return eval(expression)
	except:
		return None

def tax_calc(gross=None, net=None, rate=None, taxamt=None):
	'''
	Calculates tax (VAT) based off of a combination of two variables: gross, net, rate or tax amount. Selecting rate+taxamt can cause rounding errors.
	'''
	tax = {'gross':gross, 'net':net, 'rate':rate, 'taxamt':taxamt}
	if sum([arg != None for arg in tax.values()]) != 2:
		raise ValueError("Tax_calc requires exactly two arguments.")
	try:
		tax['gross'] = float(
			round(gross
				or try_this("tax['net'] * (1+tax['rate']/100)", tax)
				or try_this("tax['net'] + tax['taxamt']", tax)
				or try_this("tax['taxamt']/(tax['rate']/100) + tax['taxamt']", tax)
					, 2)
							)
		tax['net'] = float(
			round(net
				or try_this("tax['gross']/(1+tax['rate']/100)", tax)
				or try_this("tax['gross'] - tax['taxamt']", tax)
					, 2)
							)
		tax['taxamt'] = float(
			round(taxamt
				or try_this("tax['gross'] - tax['net']", tax)
					, 2)
							)
		tax['rate'] = float(
			round(rate
				or try_this("(tax['gross']/tax['net']-1)*100", tax)
					, 2)
							)
	except:
		raise ValueError("Tax_calc accepts only numbers as arguments.")
	return tax
	
def tax_input():
	'''
	Gets user input for the tax calculation.
	getInput() is a method from a module that performs input validation (usage: getInput(prompt_text, type, restrictions, maxlength)).
	'''
	vals = {'gross':None, 'net':None, 'rate':None, 'taxamt':None}
	answer = inp.getInput("Calculate from what (choose two)?\n" 
						"[g]ross amount\n"
						"[n]et amount\n"
						"[r]ate\n"
						"[t]ax amount\n"
						"[q]uit",
						'string', 'gnrtGNRTqQ', 2)
	if 'q' in answer.lower():
		print('Quitting...')
		return
	if answer[0] == answer[1]: #getInput() can't prevent user from entering the same letter twice
		return tax_input()
	for char in answer:
		if char.lower() == 'g':
			vals['gross'] =  inp.getInput("Gross amount: ", 'float')
		elif char.lower() == 'n':
			vals['net'] =  inp.getInput("Net amount: ", 'float')
		elif char.lower() == 'r':
			vals['rate'] =  inp.getInput("Tax rate: ", 'float', (0, 100)) # Tax rate has to fall between 0 and 100
		elif char.lower() == 't':
			vals['taxamt'] =  inp.getInput("Tax amount: ", 'float')
	tax = tax_calc(**vals)
	print('')
	for ele, val in tax.items():
		print(f'{ele}: {val}')
	input('')
	return tax_input()


if __name__ == '__main__':
	tax_input()
	input('')

In [21]:
id(exit)

140624273874800

In [60]:
import pandas as pd
import numpy as np

q = 'example'

class Pandas:

    fname = f'search_results_{q}.pkl'

    def save_to_pandas(self, fname=None):
        if fname is None:
            fname = Pandas.fname
        self.df = pd.DataFrame.from_records(self.data)
        self.df.to_pickle(fname)
        
    def create_df(self):
        clean_df = self.df.filter(['created_at', 'text', 'entities', 'favorite_count', 'retweeted', 'retweeted_status', 'user'], axis=1)
        clean_df['full_tweet'] = list(map(lambda tweet: tweet['text'] if 'extended_tweet' not in tweet else tweet['extended_tweet']['full_text'], results))
        clean_df['location'] = list(map(lambda tweet: tweet['user']['location'], results))
        clean_df['username'] = list(map(lambda tweet: tweet['user']['screen_name'], results))
        clean_df['retweeted_status'] = Updated_DF['retweeted_status'].replace(np.nan, 'no')
        print('Your dataframe is complete. Below is a sample of tweets.')
        print(clean_df['text'].head(2))
        clean_df.to_csv('clean_df.csv')
        print('Your dataframe has been saved succesfully to a CSV file.')
        print(clean_df.info())
        self.df = clean_df
            
    def retweet(self):
        print('There are', len(self.clean_df[self.clean_df['retweeted_status'] != 'no']), 'retweets in the data.')



data = np.array([(3, 'a'), (2, 'b'), (1, 'c'), (0, 'd')],
                dtype=[('col_1', 'i4'), ('col_2', 'U1')])

pandy1 = Pandas()
pandy1.data = data
pandy1.save_to_pandas()
print(pandy1.df)


   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d


In [84]:
import datetime


dt = datetime.datetime.now()

cYear = dt.year
cMonth = dt.month
cDay = dt.day

# print(cMonth, cDay, cYear)

uName = input('What is your name?: ')

# Month
while True:
    try:
        uBirthdayM = int(input('Enter your birth month: '))
        if uBirthdayM < 1 or uBirthdayM > 12:
            raise ValueError  # this will send it to the print message and back to the input option
        break
    except ValueError:
        print("Invalid Month. The month must be in the range of 1-12.")

# Day
while True:
    try:
        uBirthdayD = int(input('Enter your birth day: '))
        if uBirthdayD < 1 or uBirthdayD > 31:
            raise ValueError  # this will send it to the print message and back to the input option
        break
    except ValueError:
        print("Invalid Date. The day must be in the range of 1-31.")

# Year
while True:
    try:
        uBirthdayY = int(input('Enter your birth year: '))
        if uBirthdayY < 1 or uBirthdayY > 2021:
            raise ValueError  # this will send it to the print message and back to the input option
        break
    except ValueError:
        print("Invalid Year. The year cannot be higher than ", cYear)


uBirthday = str('{:02d}'.format(uBirthdayM)) + '/' + str(uBirthdayD) + '/' + str(uBirthdayY)


# print(uName, ' was born on ', uBirthday)

# if str(cDay) < str(uBirthdayD):
#     print('Less Than')
# elif str(cDay) > str(uBirthdayD):
#     print('Greater Than')

print(cMonth, cDay, cYear)

if cMonth > str(uBirthdayM):
    print('Birthday is coming up this year')

elif cMonth < str(uBirthdayM):
    print('Birthday has already passed')

elif cMonth == str(uBirthdayM):
    print('It is your birthday this month!')

elif str(uBirthdayM) == str(cMonth) and str(uBirthdayD) == str(cDay):
    print('Today is  your birthday, Happy Birthday!')

elif str(uBirthdayM) == str(cMonth) and str(uBirthdayD) < str(cDay):
    print("Birthday hasn't happened yet, Be patient!")

elif str(uBirthdayM) == str(cMonth) and str(uBirthdayD) > str(cDay):
    print('Birthday has already happened, Happy belated Birthday')

01 17 2021
Birthday has already passed


In [88]:
cMonth < '5'

True

In [86]:
uBirthdayM

5

In [1]:
    for row in range(7):
      for col in range(5):
       if (col == 0) or (col == 4 and (row != 0 and row != 6)) or (row == 0 or row == 6) and  (col > 0 and col  < 4 ):
        print("D", end=" ")
      else:
        print(end="")
      print()

D D D D 
D D 
D D 
D D 
D D 
D D 
D D D D 


In [4]:
indent = 4
height = 7
full = 0, 6
symbol = 'D'
fill = ' '

for row in range(height):
....if row in full:
........print(symbol * indent)
....else:
........print(f"{symbol}{fill * (indent - 1)}{symbol}")

DDDD
D   D
D   D
D   D
D   D
D   D
DDDD


In [25]:
import numpy as np 
ll =[[1,7], [2,8],[3,9], [4,10], [5,11], [6,12]]
flat = [nums[0] for nums in ll] + [nums[1] for nums in ll]
out = np.reshape(flat, (-1, 3))
print(out)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
ll[:2] + ll[1:2]


[[1, 7], [2, 8], [2, 8]]

In [13]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [2]:
student_information = [
{"name" : "anna", "class" : 11, "section" : "A", "gr" : 34596},
{"name" : "rolph", "class" : 11, "section" : "A", "gr" : 38475},
{"name" : "charlie", "class" : 9, "section" : "B", "gr" : 45964},
{"name" : "tom", "class" : 12, "section" : "F", "gr" : 48586},
]

mod_per = input("whose information do you want to modify: ")
mod_info = input("what inforation do you want to modify: ")
new_mod_info = input("please type the new information: ")

    for record in student_information:
        if mod_per == record['name']:
            record[mod_info] = new_mod_info
            break
    else:
        print(f'No record for {mod_per}')

In [ ]:
for record in student_information:
    if mod_per = record['name']:
        record[mod_info] = new_mod_info
        break
else:
    print(f'No record for {mod_per}')

In [3]:
student_information

[{'name': 'anna', 'class': 11, 'section': 'A', 'gr': 34596},
 {'name': 'rolph', 'class': 11, 'section': 'A', 'gr': 38475},
 {'name': 'charlie', 'class': '999', 'section': 'B', 'gr': 45964},
 {'name': 'tom', 'class': 12, 'section': 'F', 'gr': 48586}]

In [8]:
[4,2,6,5].index(7)

ValueError: 7 is not in list

In [9]:
help(list.index)

Help on method_descriptor:

index(self, value, start=0, stop=9223372036854775807, /)
    Return first index of value.
    
    Raises ValueError if the value is not present.



In [10]:
def t():
    return 

type(t())

NoneType

In [1]:

from itertools import cycle

WIDTH = HEIGHT = 6


def create_board(width=WIDTH, height=HEIGHT):
    return [[-1 for _ in range(width)] for _ in range(height)]

def get_play(board, player):
    while True:
        try:
            x, y = (int(numstr) 
                for numstr in input(f'Player {player} coord: ').split()
            )
        except ValueError:
            print('Invalid input')
        else:
            if 0 <= x <= width and \
                0 <= y <= height and \
                    board[x][y] == -1:
                board[x][y] = player
            else:
                print('Invalid play')

def chunker(seq, size):
    for idx in range(len(seq) - size):
        yield seq[idx: idx + size]

def win_or_draw(board):
    
    def horizontal_win(board):
        winner = -1, -1, -1
        for row_num, row in enumerate(board):
            for col_num, chunk in enumerate(chunker(row)):
                if all(num for num in chunk[1:] == chunk[0]):
                    return chunk[0], row_num, col_num

    return horizontal_win(board)
            

board = create_board()
eligible_players = [1, 2]
players = cycle(eligible_playerers)
for player in players:
    get_play(board, player)
    print(board)
    winner, x, y = win_or_draw(board)
    if winner == -999 or winner in eligible_players: 
        return winner, x, y

print(result)

Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invalid input
Invali

KeyboardInterrupt: 

In [2]:
board

[[-1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1]]

In [20]:
def chunker(seq, size):
    for idx in range(len(seq) - size + 1):
        yield seq[idx: idx + size]

In [21]:
for chunk in chunker([1,2,3,4,5,6,7,8,9,10,11,12], 3):
    print(chunk)

[1, 2, 3]
[2, 3, 4]
[3, 4, 5]
[4, 5, 6]
[5, 6, 7]
[6, 7, 8]
[7, 8, 9]
[8, 9, 10]
[9, 10, 11]
[10, 11, 12]
